### ISSUE TITLE
Abstract encoding compatibility

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/pushdata-bitcoin#1]

**Comment by dcousens** [comment]
@fanatid if you have the time,  obviously not priority,  just figured I'd ask just in case :)

**Comment by fanatid** [comment]
@dcousens is it reduced version of [bitcoinjs/varuint-bitcoin](https://github.com/bitcoinjs/varuint-bitcoin)?

**Comment by dcousens** [comment]
@fanatid no,  its literally just the pushdata int encoding

**Comment by fanatid** [comment]
okay, don't you want add similar lines https://github.com/bitcoinjs/varuint-bitcoin/blob/e1a13902e25a4338c838ead8e5290dc8cd44f499/index.js#L11-L15 ?

**Comment by dcousens** [comment]
@fanatid indeed I do,  I just needed a 1:1 API so I could drop-it-in... now I'll get it up to abstract encoding

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/pushdata-bitcoin/pull/3
